### ISSUE TITLE
Bug "KeyError: 'title'"

### ISSUE THREAD

**Issue by alabrazi** [msdslab/automated-systematic-review#54]
Run any of the following commandes : 
(ml) ALAAs-MBP:~ alaabarazi$ asr simulate citation.csv
or
(ml) ALAAs-MBP:~ alaabarazi$ asr simulate citation.ris
or
(ml) ALAAs-MBP:~ alaabarazi$ asr oracle citation.ris
or
(ml) ALAAs-MBP:~ alaabarazi$ asr oracle citation.csv

Got error
`

Using lstm_base model
Start review in 'simulate' mode.
Traceback (most recent call last):
  File "/Users/alaabarazi/miniconda3/envs/ml/lib/python3.6/site-packages/pandas/core/indexes/base.p
y", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHash
Table.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHash
Table.get_item

KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alaabarazi/miniconda3/envs/ml/bin/asr", line 11, in <module>
    sys.exit(main())
  File "/Users/alaabarazi/miniconda3/envs/ml/lib/python3.6/site-packages/asr/__main__.py", line 171
, in main
    _review_simulate()
  File "/Users/alaabarazi/miniconda3/envs/ml/lib/python3.6/site-packages/asr/__main__.py", line 160
, in _review_simulate
    review_simulate(path, **args_dict)
  File "/Users/alaabarazi/miniconda3/envs/ml/lib/python3.6/site-packages/asr/review.py", line 270,
in review_simulate
    review(dataset, mode='simulate', **kwargs)
  File "/Users/alaabarazi/miniconda3/envs/ml/lib/python3.6/site-packages/asr/review.py", line 106,
in review
    texts, labels = read_data(dataset)
  File "/Users/alaabarazi/miniconda3/envs/ml/lib/python3.6/site-packages/asr/readers.py", line 49,
in read_data
    texts = (df['title'].fillna('') + ' ' + df['abstract'].fillna(''))
  File "/Users/alaabarazi/miniconda3/envs/ml/lib/python3.6/site-packages/pandas/core/frame.py", lin
e 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/alaabarazi/miniconda3/envs/ml/lib/python3.6/site-packages/pandas/core/indexes/base.p
y", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHash
Table.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHash
Table.get_item
KeyError: 'title'
`

**Comment by qubixes** [comment]
Do your files have a column called "title"? Perhaps it was translated somehow?
